version: "3.9"
services:
    web:
        build: WeatherArchive/
        ports:
            - "8080:80"
        depends_on:
            - db
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            Logging__Console__FormatterName: Simple
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Pass228228"
            ACCEPT_EULA: "Y"